### ISSUE TITLE
Publish the module on PSGallery

### ISSUE THREAD

**Issue by vedantmgoyal9** [jedieaston/WinGetHelpers#3]
Please publish the module on PSGallery.

**Comment by jedieaston** [comment]
I've thought about it, and the problem is that I haven't really written documentation for it yet. I've been meaning to work on that (maybe in the next couple weeks now that I finally have a little bandwidth).

Right now, you should be able to use it by cloning it into your ~/Documents/WindowsPowerShell/Modules directory. If there's a specific usecase that doesn't work for I can move publishing it up on my todo list.

**Comment by vedantmgoyal9** [comment]
@jedieaston I've opened a PR that adds some docs, and other things.

**Comment by vedantmgoyal2009** [comment]
So, now can the module be published?

**Comment by vedantmgoyal9** [comment]
Closing in favor of https://github.com/jedieaston/winget-lib
